package com.nfpenterprise.projectValhalla.constants.character;

public enum CharacterAdjectives {
	BIGOTED ("bigoted"),
	BITCHY ("bitchy"),
	BLUNT ("blunt"),
	BOISTEROUS ("boisterous"),
	BOSSY ("bossy"),
	BRAVE("brave"),
	CALLOUS("callous"),
	CAUTIOUS("cautious"),
	CHARMING("charming"),
	CHEERFUL("cheerful"),
	CHURLISH("churlish"),
	COLD("cold"),
	COMPOSED("composed"),
//     "conceited",
//     "condescending",
//     "confident",
//     "conscientious",
//     "cool-headed",
//     "courageous",
//     "crabby",
//     "crass",
//     "critical",
//     "cruel",
//     "cunning",
//     "curious",
//     "cynical",
//     "decisive",
//     "dependable",
//     "determined",
//     "driven",
//     "fearless",
//     "flamboyant",
//     "flirtatious",
//     "friendly",
//     "gruff",
//     "headstrong",
//     "hot-headed",
//     "lazy",
//     "loud",
//     "Machiavellian",
//     "moody",
//     "philosophical",
//     "pompous",
//     "pretty chill",
//     "romantic",
//     "selfish",
//     "sensitive",
//     "tactless",
//     "thoughtful",
//     "wary",
//     "depressed",
//     "delightful",
//     "demure",
//     "diligent",
//     "disruptive",
//     "discerning",
//     "dramatic",
//     "dutiful",
//     "frank",
//     "funny",
//     "fussy",
//     "generous",
//     "gentle",
//     "gloomy",
//     "grave",
//     "grouchy",
//     "guarded",
//     "hateful",
//     "helpful",
//     "hot-headed",
//     "hypercritical",
//     "level-headed",
//     "mean",
//     "methodical",
//     "meticulous",
//     "miserable",
//     "motivated",
//     "morose",
//     "naive",
//     "nosy",
//     "peaceful",
//     "pensive",
//     "plain-speaking",
//     "playful",
//     "plucky",
//     "positive",
//     "proud",
//     "prejudiced",
//     "quick-tempered",
//     "reliable",
//     "reluctant",
//     "resentful",
//     "resourceful",
//     "respectful",
//     "restless",
//     "sassy",
//     "sentimental",
//     "short-tempered",
//     "snobby",
//     "sombre",
//     "sophisticated",
//     "spiteful",
//     "soulless",
//     "stern",
//     "stoic",
//     "surly",
//     "sweet",
//     "suspicious",
//     "talented",
//     "warm-hearted",
//     "wary",
//     "well-intentioned",
//     "adventurous",
//     "agreeable",
//     "ambitious",
//     "anxious",
//     "apathetic",
//     "argumentative",
//     "assertive",
//     "attentive",
//     "impulsive",
//     "intolerant",
//     "inventive",
//     "overemotional",
//     "unpredictable",
//     "eager",
//     "easy-going",
//     "egotistical",
//     "emotional",
//     "enterprising",
//     "enthusiastic",
//     "excitable",
//     "impatient",
//     "impetuous",
//     "inconsiderate",
//     "insensitive",
//     "irritable",
//     "obnoxious",
//     "old-fashioned",
//     "outgoing",
//     "outspoken",
//     "unbalanced",
//     "unstable",
//     "absent minded",
//     "melodramatic",
//     "paranoid",
//     "chipper",
//     "passive-aggressive",
//     "amicable",
//     "broad-minded",
//     "compassionate",
//     "considerate",
//     "diplomatic",
//     "faithful",
//     "hard-working",
//     "modest"
	;
	private final String adjectiveName;
	
	CharacterAdjectives(String adjectiveName) {
		this.adjectiveName = adjectiveName;
	}
	
	public String getName() {
		return adjectiveName;
	}
	
}